### ISSUE TITLE
v0.6-rc2 fails to precompile often

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Atom.jl#86] opened 2017-05-19 17:18 UTC
Example:

```julia
using DifferentialEquations

INFO: Recompiling stale cache file C:\Users\Chris\.julia\lib\v0.6\Combinatorics.ji for module Combinatorics.
WARNING: The call to compilecache failed to create a usable precompiled cache file for module Combinatorics. Got:
WARNING: Module Iterators uuid did not match cache file.
```

Combinatorics and DifferentialEquations are just fine though. And this all precompiles just fine from the REPL. Somehow Juno being involved is introducing a bunch of precompilation bugs.

**Comment by MikeInnes** [comment] 2017-05-19 17:20
I've seen this a lot on 0.6. Must be a precomp bug but I'm not sure how to make it reproducible; if you retry it tends to go away.

**Comment by ChrisRackauckas** [comment] 2017-05-19 17:21
>if you retry it tends to go away.

I have to try it a few times in the REPL for it to go away. If I try from Juno, it will keep happening.

**Comment by MikeInnes** [comment] 2017-05-19 17:23
In that case it'd be well worth reporting it to Base

**Comment by pfitzseb** [comment] 2017-06-01 23:00
Seems to be fixed now.

**Closed by pfitzseb** 2017-06-01 23:00 UTC
