### ISSUE TITLE
Newly updated Atom.jl fails to precompile.

### ISSUE THREAD

**Issue by mkborregaard** [JunoLab/Atom.jl#23] opened 2016-01-15 08:13 UTC
I use ```using Atom``` and get
```
INFO: Precompiling module Atom...
ERROR: LoadError: ArgumentError: Blink not found in path
 in compilecache at loading.jl:377
 in require at /usr/local/lib/julia/sys.dylib
 in include at /usr/local/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /usr/local/lib/julia/sys.dylib
 in _start at /usr/local/lib/julia/sys.dylib
while loading /Users/michael/.julia/v0.4/Atom/src/Atom.jl, in expression starting on line 5
ERROR: Failed to precompile Atom to /Users/michael/.julia/lib/v0.4/Atom.ji
 in error at /usr/local/lib/julia/sys.dylib
 in compilecache at loading.jl:384
 in require at /usr/local/lib/julia/sys.dylib
```

I am on Julia version 0.4.3-pre+6.
Thanks,
Michael

**Comment by JonnyCBB** [comment] 2016-01-19 10:24
I had exactly the same error. I then added the Blink package `Pkg.add(Blink)` but now I get a different error: 

```
julia> using Atom
INFO: Precompiling module Atom...

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x64f05780 -- jl_is_type at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_is_type at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_load_and_lookup at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_compile at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_trampoline at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
__init__ at C:\Users\jonathan\.julia\v0.4\Blink\src\content\server.jl:76
jlcall___init___3201 at  (unknown line)
jl_apply_generic at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_module_run_initializer at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_deserialize_lambdas_from_mod at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_restore_incremental at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
_require_from_serialized at loading.jl:84
jlcall__require_from_serialized_2711 at  (unknown line)
jl_apply_generic at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
_require_from_serialized at loading.jl:109
require at loading.jl:219
jlcall_require_2610 at  (unknown line)
jl_apply_generic at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_init_serializer at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_eval_module_expr at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_load_ at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:304
jl_apply_generic at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
anonymous at none:2
jl_eval_with_compiler_p at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
process_options at client.jl:257
_start at client.jl:378
jlcall__start_1838 at  (unknown line)
jl_apply_generic at C:\Users\jonathan\AppData\Local\Julia-0.4.3\bin\libjulia.dll (unknown line)
unknown function (ip: 00000000004018D0)
unknown function (ip: 00000000004028AB)
unknown function (ip: 000000000040140C)
unknown function (ip: 000000000040153B)
BaseThreadInitThunk at C:\WINDOWS\system32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
ERROR: Failed to precompile Atom to C:\Users\jonathan\.julia\lib\v0.4\Atom.ji
 in error at error.jl:21
```
I am on Julia version 0.4.3
Cheers

**Comment by mkborregaard** [comment] 2016-01-19 10:24
Solved with the newest update. Thanks.

**Comment by mkborregaard** [comment] 2016-01-19 10:26
I have Blink installed. But I still get the original error.

**Comment by rnoxy** [comment] 2016-01-19 21:13
Similar problem under Julia 0.4.3 (binary version for Linux64) or 0.4.4-pre+2 (built on Ubuntu).

```
julia> using Atom
INFO: Precompiling module Atom...

signal (11): Naruszenie ochrony pamięci
unknown function (ip: 0x7f3b5cd91a50)
unknown function (ip: 0x7f3b5cdd068a)
unknown function (ip: 0x7f3b5cdd085c)
jl_trampoline at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
__init__ at /home/rno/.julia/v0.4/Blink/src/content/server.jl:76
jlcall___init___24594 at  (unknown line)
jl_apply_generic at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
jl_module_run_initializer at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f3b5ce0a66f)
jl_restore_incremental at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
_require_from_serialized at loading.jl:84
jlcall__require_from_serialized_24217 at  (unknown line)
jl_apply_generic at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
require at ./loading.jl:225
unknown function (ip: 0x7f3b59eec73c)
jl_apply_generic at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f3b5ce1129d)
unknown function (ip: 0x7f3b5ce1222b)
unknown function (ip: 0x7f3b5ce1203d)
unknown function (ip: 0x7f3b5ce12722)
unknown function (ip: 0x7f3b5ce12375)
unknown function (ip: 0x7f3b5ce12ca9)
jl_load at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
include at ./boot.jl:261
jl_apply_generic at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:304
jl_apply_generic at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f3b5cdfd953)
unknown function (ip: 0x7f3b5cdfcd91)
unknown function (ip: 0x7f3b5ce11fb8)
jl_toplevel_eval_in at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at none:2
unknown function (ip: 0x7f3b5ce1207b)
jl_toplevel_eval_in at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
process_options at ./client.jl:257
_start at ./client.jl:378
unknown function (ip: 0x7f3b59ed3749)
jl_apply_generic at /mnt/multimedia/soft/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x401ae9)
unknown function (ip: 0x4016bf)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401705)
unknown function (ip: (nil))
```

**Comment by mkborregaard** [comment] 2016-01-20 12:30
Problem persists after updating julia to 0.4.4-pre+2 on my Mac OS X (Capitan) machine as well. Is this working for anyone, or are we three the only people having problems?

**Comment by mkborregaard** [comment] 2016-01-20 12:36
This appears to be a problem in Blink.jl, not Atom.jl. It is listed as 'build failing' on OS X and Linux at its github page. I have opened the issue there.

**Comment by rnoxy** [comment] 2016-01-20 12:36
I have found that the problem is not with Atom.jl but with Blink.
I have tried to build Blink package for Julia and run "using Blink", and I obtained exactly the same segmentation fault.

I have the following solution.
````
in bash
  rm -rf ~/.julia
in julia
  Pkg.update()
  Pkg.add("Blink")
  Pkg.build("Blink")
  using Blink;
  # precompilation is now succesfull
  Pkg.add("Atom");
  using Atom
````

**Comment by Varanas** [comment] 2016-01-20 12:38
I'm pretty sure this is a problem with some dependency. You could try checking out the latest master of Blink. jl, CodeTools.jl and possibly some others (don't know which one fixed that for me from the top of my head).

**Comment by Varanas** [comment] 2016-01-20 12:46
I think macrotools.jl may be the culprit, can't test that right now though.

**Comment by mkborregaard** [comment] 2016-01-20 12:50
No, ```using Macrotools``` did not raise an error.
```using Blink``` does reproduce the segmentation fault. I would like to try out @rnoxy 's suggestion, but do not want to clobber my entire julia library. Simply ```Pkg.rm("Blink")``` and then going through the above procedure does not solve the problem.

**Comment by Varanas** [comment] 2016-01-20 12:54
Yeah,  I meant that you may need to `Pkg. checkout` MacroTools.jl.

**Comment by mkborregaard** [comment] 2016-01-20 12:57
Ahh, OK, got you. I tried it out:

```
Pkg.checkout("Blink")
Pkg.checkout("MacroTools")
Pkg.build("MacroTools")
Pkg.build("Blink")
using MacroTools
using Blink
```
gives the response:
```
INFO: Recompiling stale cache file /Users/michael/.julia/lib/v0.4/Lazy.ji for module Lazy.
INFO: Recompiling stale cache file /Users/michael/.julia/lib/v0.4/MacroTools.ji for module MacroTools.
WARNING: Module MacroTools uuid did not match cache file
WARNING: deserialization checks failed while attempting to load cache from /Users/michael/.julia/lib/v0.4/Lazy.ji
INFO: Precompiling module Lazy...
INFO: Recompiling stale cache file /Users/michael/.julia/lib/v0.4/Lazy.ji for module Lazy.
WARNING: Module MacroTools uuid did not match cache file
ERROR: __precompile__(true) but require failed to create a precompiled cache file
 in require at /usr/local/lib/julia/sys.dylib
 in stale_cachefile at loading.jl:441
 in recompile_stale at loading.jl:458
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at /usr/local/lib/julia/sys.dylib
 in require at /usr/local/lib/julia/sys.dylib
 in stale_cachefile at loading.jl:441
 in recompile_stale at loading.jl:458
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at /usr/local/lib/julia/sys.dylib
 in require at /usr/local/lib/julia/sys.dylib
```

**Comment by mkborregaard** [comment] 2016-01-20 13:02
But quitting and restarting julia, ```using Atom```runs without a problem! Thanks!

**Comment by Varanas** [comment] 2016-01-20 13:07
You're welcome! 
I'll reopen this just so someone tags a new version of `MacroTools.jl` soon ;-)

**Comment by mkborregaard** [comment] 2016-01-20 13:08
:+1:

**Comment by Varanas** [comment] 2016-01-21 21:41
cc: @one-more-minute. :)

**Comment by one-more-minute** [comment] 2016-01-27 14:07
*Someone* ;)

Yup, this should be fixed now, let me know if there are any problems.

**Closed by one-more-minute** 2016-01-27 14:07 UTC

**Comment by Varanas** [comment] 2016-01-27 16:32
Hehe yep. I thought MacroTools was in the JunoLab group... :D
